### ISSUE TITLE
GB language files in the raw folder

### ISSUE THREAD

**Issue by MiinaNo** [cldf-datasets/uratyp#11]
@xrotwang would it be possible to move the GB questionnaires in the `raw` folder into the separate GB folder (as done with the UT questionnaire)? Or does it mess up something for you? I wanted to add some words to the `README.md` file about the GB tables but it would be easier if they would be organized following the same logic

We were also thinking with @JakeJing  that maybe we could also used the language names in the files names (at the moment there are glottocodes)? 

Another thing that has been puzzling me is that for some reason there are two files with Estonian data, see RK-MN_esto1258.tsv.csv and RK_fore1265.tsv.csv Could we remove the latter (i.e. that does not have my initials in the file name)? The RK-MN is the correct one.

**Comment by xrotwang** [comment]
Yes. In fact, the GB questionnaires can be removed entirely, because - after @JakeJing told me about https://github.com/cldf-datasets/uratyp/blob/main/raw/GB/Finaldata.csv , I used this as the source for the GB data in the CLDF dataset. We can think about if/how to bring GB questionnaires back in once we decide to re-sync the data between UtraTyp and GB.
